# Generated by Django 3.2.5 on 2021-12-11 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='date_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 11, 23, 18, 8, 805352)),
        ),
    ]
